runtime: python
env: flex

runtime_config:
  operating_system: ubuntu22
  runtime_version: "3.12"

entrypoint: streamlit run main.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

