runtime: python39

env_variables:
  GOOGLE_CLOUD_PROJECT: recuruiter-chatbot-jh

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.8

resources:
  cpu: 2
  memory_gb: 1
  disk_size_gb: 2

handlers:
- url: /.*
  script: auto
  secure: always

entrypoint: streamlit run main.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?tests/.*$
- ^(.*/)?test_.*\.py$
- ^(.*/)?.*_test\.py$
- ^(.*/)?pytest\.ini$
- ^(.*/)?run_tests\.py$
- ^(.*/)?eda/.*$
- ^(.*/)?\.git/.*$
- ^(.*/)?README\.md$
- ^(.*/)?PROJECT_STATUS\.md$
- ^(.*/)?CLAUDE\.local\.md$