name: recruiter-chatbot-env
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.10
  
  # Streamlit for UI
  - streamlit
  
  # LangChain for document processing
  - langchain
  - langchain-community
  
  # ChromaDB for vector store (minimal install)
  - chromadb
  - onnxruntime  # For embeddings
  
  # Basic data handling
  - pandas
  - numpy
  
  # Testing (dev dependency)
  - pytest
  
  # Pip dependencies for packages not in conda
  - pip
  - pip:
    - sentence-transformers  # Alternative to ONNX if needed